### ISSUE TITLE
Your application should have a basic REST interface.

### ISSUE THREAD

**Issue by vasekstebra** [VaclavStebra/pa165-booking-manager#76]
(DELETE http://localhost:8080/pa165/rest/hotel/1 not working, UPDATE not implemented) At least one entity and operations on that entity must be exposed.

**Comment by vasekstebra** [comment]
In my opinion delete isn't working when you try to delete hotel that has rooms. Which is in correct I think and would change it.

**Comment by Dominick1993** [comment]
If anyone is fixing this issue, please also fix the Javadoc for createHotel, Endpoint should be changed from `http://localhost:8080/pa165/rest/hotel/create` to `http://localhost:8080/pa165/rest/hotel/`. Thanks!

**Comment by vasekstebra** [comment]
I will fix it.
